### PR TITLE
feat(Device): Add support for left/right touchpad events for the OrangePi Neo.

### PR DESCRIPTION
**Pull request by pastaq**

### CODE REVIEW

**Comment by pastaq** [comment]
Resolves #119

**Comment by philmmanjaro** [comment]
I would rather fix the mount_matrix on a separate PR as intended before and wait with this PR until we have a solution to use the touchpads as Mouses when the Gamepad profile doesn't support touch in its controller. This would be Xbox Controller as an example. Also when switching on desktop mode the regular mouse is gone.

We might want to find a solution also to only activate them when running a steam session or gamescope. Has some aspects we can discuss ...

**Comment by pastaq** [comment]
Don't merge until we can translate Touchpad events to all other relevant events (Mouse, Joystick, add a virtual touchpad device)

**Comment by pastaq** [comment]
I modified the device profile for the OrangePi NEO so it wont capture the touchpads. These lines can be uncommented once we add touchpads to the schema and/or add the steam deck controller as the default target. This removes the need to wait for this PR and makes #120 irrelevant.

**Review by ShadowApex — APPROVED** [review]

**Comment by philmmanjaro** [comment]
OK, is a good compromise for now.

**Pull request merged**
