### PR TITLE
feat(SteamDeckTarget): add Steam Deck Controller target device through USB emulation

### PR DESCRIPTION
**Pull request by ShadowApex**
Tested with Sony DualSense source device.

image

image

### CODE REVIEW

**Review by pastaq — APPROVED** [review]
Works as expected on the Legion Go and OrangePi Neo. We should verify stability before merging.

**Comment by philmmanjaro** [comment]
Will test this also on my end and will give feedback. Might also tell the vendor to test on their end at factory level.

**Comment by philmmanjaro** [comment]
@pastaq initial feedback on the Neo 8840u: I can see the SteamDeck controller after adding the pull requests to InputPlumber and OpenGamepadUI. When I go to controller settings and begin testing I see buttons working and triggers too. Visual feedback on the SteamDeck controller picture is not always given. Pressed buttons stay highlighted on the picture. When using the touchpads as trackpads no feedback is given in the UI. However I see a regular mouse movement and the colours switch to desktop mode as if you use a mouse.

We might do debug this more.

**Comment by philmmanjaro** [comment]
After adding [a.patch](https://github.com/user-attachments/files/16371800/a.patch.txt) the touchpads got detected as Steam Controller trackpads. I assume OrangePi didn't adopt their device renaming on the current firmware I test on my 8840u device.

**Comment by philmmanjaro** [comment]
QAM button acts as GUIDE button for some odd reason unless I have to learn on how the steam buttons should work. If I select battery symbol and open it once I can shuffle between left and QAM menu by pressing button 6 with the gamepad symbol on the Neo.

**Comment by philmmanjaro** [comment]
For some reason **Street Fighter 6 Demo** didn't work in SteamDeck profile. When switching to DS5 or X it worked.

**Comment by pastaq** [comment]
> QAM button acts as GUIDE button for some odd reason unless I have to learn on how the steam buttons should work. If I select battery symbol and open it once I can shuffle between left and QAM menu by pressing button 6 with the gamepad symbol on the Neo.

We need to add a different capability map for the deck target. currently it gets converted into the chord for qam, which is guide + a. If we remove that it will work as expected but break qam for other targets. This is a WIP.

**Review by pastaq — APPROVED** [review]
Send it

**Comment by philmmanjaro** [comment]
I noticed that sleep is totally broken when enabling the profile. More info in the issue: https://github.com/ShadowBlip/InputPlumber/issues/165

**Comment by pastaq** [comment]
> I noticed that sleep is totally broken when enabling the profile. More info in the issue: #165

You didn't have to post this multiple times.

**Pull request merged**
